---
title: "Hexbin plots"
output:
  html_document:
    toc: false
    number_sections: false
    df_print: paged
    code_download: true
    highlighter: null
---

```{r setup, eval=TRUE, include=FALSE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
chooseCRANmirror(graphics=FALSE, ind=133)
source("source/plots-overview.R")
```
___

Page last updated: `r format(Sys.time(), '%d %B, %Y')`

\  

# Examples {#hexbins .tabset}

## Hexbin {#hexbin}
```{r hexbin, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### Heatmap hexbin
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_hex() +
  scale_fill_gradientn(colours = continuous_wes_pal, 
                      breaks = c(0, 2500, 5000),
                      limits = c(0, 5000),
                      guide = "colourbar") +
  guides(fill = guide_colourbar(barwidth = 15, 
                                barheight = 1,
                                ticks = FALSE,
                                title = "",
                                label.hjust = 1)) +
  my_theme() 
```