---
title: "Line plots"
output:
  html_document:
    toc: false
    number_sections: false
    df_print: paged
    code_download: true
    highlighter: null
---

```{r setup, eval=TRUE, include=FALSE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
chooseCRANmirror(graphics=FALSE, ind=133)
source("source/plots-overview.R")
```

___
Page last updated: `r format(Sys.time(), '%d %B, %Y')`

\  

# Examples {#line_plots .tabset}

## One variable {#line}
```{r line, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### line plot
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_line(aes(x = votes, y = rating),
            color = discrete_wes_pal[1]) +
  my_theme() 
```

## One variable shown by colour {#line_group_colour}
```{r line_group_colour, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### line plot - with groups defined by colour and size
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_line(aes(colour = Genre)) +
  scale_color_manual(values = discrete_wes_pal) +
  guides(colour = guide_legend(override.aes = list(size = 5),
                               title = "",
                               label.hjust = 0,
                               label.vjust = 0.5)) +
    my_theme() 
```

## One variable shown by size {#line_group_size}
```{r line_group_size, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### line plot - with groups defined by colour and size
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_line(aes(size = Genre),
            color = discrete_wes_pal[1]) +
  guides(size = guide_legend(title = "",
                             label.hjust = 0,
                             label.vjust = 0.5)) +
  my_theme()
```

## One variable shown by colour and size {#line_group_colour_size}
```{r line_group_colour_size, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### line plot - with groups defined by colour and size
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_line(aes(colour = Genre, size = Genre)) +
  scale_color_manual(values = discrete_wes_pal) +
  guides(colour = guide_legend(override.aes = list(size=5),
                               title = "",
                               label.hjust = 0,
                               label.vjust = 0.5)) +
    my_theme() 
```

## Two variables shown by colour and size {#line_diff_group_colour_size}
```{r line_diff_group_colour_size, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
## line plot - with groups defined by colour and rating by size
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_line(aes(colour = Genre, size = rating)) +
  scale_color_manual(values = discrete_wes_pal) +
  guides(colour = guide_legend(override.aes = list(size=5),
                               title = "",
                               label.hjust = 0,
                               label.vjust = 0.5)) +
  guides(size = guide_legend(label.hjust = 0,
                             label.vjust = 0.5)) +
    my_theme() 
```
