---
title: "Scatter plots"
output:
  html_document:
    toc: false
    number_sections: false
    df_print: paged
    code_download: true
    highlighter: null
---

```{r setup, eval=TRUE, include=FALSE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
chooseCRANmirror(graphics=FALSE, ind=133)
source("source/plots-overview.R")
```

___
Page last updated: `r format(Sys.time(), '%d %B, %Y')`

\  

# Examples {#scatter_plots .tabset}

## One variable {#scatter}
```{r scatter, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### scatter plot
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_point(aes(x = votes, y = rating),
             color = discrete_wes_pal[1]) +
  my_theme() 
```

## One variable shown by colour {#scatter_group_colour}
```{r scatter_group_colour, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### scatter plot - with multiple groups
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_point(aes(colour = Genre))  +
  scale_color_manual(values = discrete_wes_pal) +
  guides(colour = guide_legend(override.aes = list(size = 5),
                               title = "",
                               label.hjust = 0,
                               label.vjust = 0.5)) +
    my_theme() 
```

## One variable shown by size {#scatter_group_size}
```{r scatter_group_size, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### scatter plot - with groups defined by size
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_point(aes(size = Genre),
             color = discrete_wes_pal[1]) +
  guides(size = guide_legend(title = "",
                               label.hjust = 0,
                               label.vjust = 0.5)) +
  my_theme()
```

## Scatter plot with line of fit and ci {#scatter_fit}
```{r scatter_fit, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### scatter plot - with stat_smooth function with lines of fit and CI
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_point(aes(colour = Genre)) +
  scale_color_manual(values = discrete_wes_pal) +
  stat_smooth(aes(colour = Genre),
              alpha = 0.2,
              show.legend = FALSE) +
  guides(colour = guide_legend(override.aes = list(size = 5),
                               title = "",
                               label.hjust = 0,
                               label.vjust = 0.5)) +
  my_theme()
```

## Grouped plots - facet_grid() {#scatter_facet_grid}
```{r scatter_facet_grid, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### scatter plot - individual plots for each group horizontal
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_point(aes(colour = Genre)) +
  scale_color_manual(values = discrete_wes_pal) +
  facet_grid(Genre ~ .) + # facet_grid makes horizontal grids
  guides(colour = guide_legend(override.aes = list(size = 5),
                               title = "",
                               label.hjust = 0,
                               label.vjust = 0.5)) +
  my_theme() +
  theme(
    strip.text.y = element_blank()
    )
```

## Grouped plots - facet_wrap() {#scatter_facet_wrap}
```{r scatter_facet_wrap, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### scatter plot - individual plots for each group in defined number of columns
ggplot(data = movies, 
       aes(x = votes, y = rating)) +
  geom_point(aes(colour = Genre)) +
  scale_color_manual(values = discrete_wes_pal) +
  facet_wrap(~Genre, ncol=4) + # facet_wrap makes columns of n length
  guides(colour = guide_legend(override.aes = list(size = 5),
                               title = "",
                               label.hjust = 0,
                               label.vjust = 0.5)) +
  coord_flip() + # flips the x and y axis
  my_theme() +
  theme(
    strip.text.x = element_blank()
  )
```
