---
title: "Density plots"
output:
  html_document:
    toc: false
    number_sections: false
    df_print: paged
    code_download: true
    highlighter: null
---

```{r setup, eval=TRUE, include=FALSE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
chooseCRANmirror(graphics=FALSE, ind=133)
source("source/plots-overview.R")
```
___

Page last updated: `r format(Sys.time(), '%d %B, %Y')`

\  

# Examples {#density_plots .tabset}

## Density plot {#density}
```{r density, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### Density plot
ggplot(data = movies, 
       aes(x = rating)) + 
  ylab("Density of Movie Rating") + 
  xlab("Score (out of 10)") +
  geom_density(color = discrete_wes_pal[1], 
               fill = discrete_wes_pal[1], 
               alpha = 1) + 
  my_theme()
```

## Density plot - facet_wrap() {#density_facet_wrap}
```{r density_facet_wrap, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### Density plot - with multiple plots for each group
ggplot(data = movies, 
       aes(x = length, fill = Genre, color = Genre)) +
  geom_density(alpha = 1) +
  xlim(0,300) + 
  facet_wrap(~ Genre, ncol = 4) +
  ylab("Density of length of film)") +
  xlab("Length of film (minutes)") +
  scale_fill_manual(values = discrete_wes_pal) +
  scale_color_manual(values = discrete_wes_pal) +
  guides(fill = guide_legend(override.aes = list(size = 5),
                               title = "",
                               label.hjust = 0,
                               label.vjust = 0.5),
         color = FALSE) +
  my_theme() +
  theme(
    strip.text.x = element_blank()
    )
```
