---
title: "Heatmaps"
output:
  html_document:
    toc: false
    number_sections: false
    df_print: paged
    code_download: true
    highlighter: null
---

```{r setup, eval=TRUE, include=FALSE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
chooseCRANmirror(graphics=FALSE, ind=133)
source("source/plots-overview.R")
```
___

Page last updated: `r format(Sys.time(), '%d %B, %Y')`

\  

# Examples {#heatmap .tabset}

## ggcorrplot {#ggcorrplot}
```{r ggcorrplot, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### Heatmap - ggcorrplot
library(ggcorrplot)

ggcorrplot(corr = matrix_data,
           method = "square",
           title = "",
           show.legend = TRUE,
           legend.title = FALSE,
           show.diag = TRUE,
           outline.color = NA,
           colors = continuous_wes_pal,
           hc.order = FALSE,
           lab = FALSE
           ) +
  scale_fill_gradientn(colours = continuous_wes_pal, 
                       breaks = c(0, 1),
                       limits = c(0, 1),
                       guide = "colourbar") +
  guides(fill = guide_colourbar(barwidth = 15, 
                                barheight = 1,
                                ticks = FALSE,
                                title = "",
                                label.hjust = 1)) +
  my_theme() +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(angle = 270),
    axis.ticks = element_blank()
  )
```

## corrr - network_plot
```{r corrr, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### corrrr - network_plot
library(corrr)

network_plot(matrix_data,
             legend = TRUE,
             colours = continuous_wes_pal,
             repel = TRUE,
             curved = TRUE,
             min_cor = 0.1) +
  scale_fill_gradientn(colours = continuous_wes_pal, 
                       breaks = c(0, 1),
                       limits = c(0, 1),
                       guide = "colourbar") +
  guides(fill = guide_colourbar(barwidth = 15, 
                                barheight = 1,
                                ticks = FALSE,
                                title = "",
                                label.hjust = 1)) +
  my_theme() +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank()
  )


```
