---
title: "Histograms"
output:
  html_document:
    toc: false
    number_sections: false
    df_print: paged
    code_download: true
    highlighter: null
---

```{r setup, eval=TRUE, include=FALSE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
chooseCRANmirror(graphics=FALSE, ind=133)
source("source/plots-overview.R")
```
___

Page last updated: `r format(Sys.time(), '%d %B, %Y')`

\  

# Examples {#histograms .tabset}

## Histogram {#histogram}
```{r histogram, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### Histogram
ggplot(data = movies, 
       aes(year)) + 
  geom_histogram(binwidth = 1, alpha = 1,
             color = discrete_wes_pal[1],
             fill = discrete_wes_pal[1]) + 
  xlab("Year") + ylab("Number of movies produced") +
  my_theme()
```

## Histogram with a single variable shown by colour {#histogram_group_colour}
```{r histogram_group_colour, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### Histogram - with groups defined by colours
ggplot(data = movies, 
       aes(year, 
           fill = Genre)) + 
  geom_histogram(binwidth = 1, 
                 alpha = 1) + 
  xlab("Year") + 
  ylab("Number of movies produced") +
  scale_fill_manual(values = discrete_wes_pal) +
  guides(fill = guide_legend(override.aes = list(size = 5),
                               title = "",
                               label.hjust = 0,
                               label.vjust = 0.5)) +
  my_theme()
```
