---
title: "QQ plot"
output:
  html_document:
    toc: false
    number_sections: false
    df_print: paged
    code_download: true
    highlighter: null
---

```{r setup, eval=TRUE, include=FALSE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
chooseCRANmirror(graphics=FALSE, ind=133)
source("source/plots-overview.R")
```
___

Page last updated: `r format(Sys.time(), '%d %B, %Y')`

\  

# Examples {#qqplot .tabset}

For these plots we will use the [GWAS data](#gwas_data).

```{r eval=TRUE, include=TRUE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
head(gwas_data)
```

\  

## gg.qqplot() 

```{r qq_plot, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### Packages
library(ggplot2)

##### Plotting variables
point_colour <- discrete_wes_pal[1]
point_size <- 2
point_transparency <- 0.8

##### Plot
gg.qqplot <- function(ps, ci = 0.95) {
  n  <- length(ps)
  df <- data.frame(
    observed = -log10(sort(ps)),
    expected = -log10(ppoints(n)),
    clower   = -log10(qbeta(p = (1 - ci) / 2, shape1 = 1:n, shape2 = n:1)),
    cupper   = -log10(qbeta(p = (1 + ci) / 2, shape1 = 1:n, shape2 = n:1))
  )
  log10Pe <- expression(paste("Expected -log"[10], plain(P)))
  log10Po <- expression(paste("Observed -log"[10], plain(P)))
  ggplot(df) +
    geom_point(aes(expected, observed), alpha = point_transparency, size = point_size, colour = point_colour) +
    geom_abline(intercept = 0, slope = 1, alpha = 0.5) +
    geom_line(aes(expected, cupper), linetype = 2) +
    geom_line(aes(expected, clower), linetype = 2) +
    xlab(log10Pe) +
    ylab(log10Po) +
  
  # Customise the theme:
    my_theme() +
    theme(
    axis.text.x = element_text(hjust = 0.5,
                               vjust = 1),
    axis.text.y = element_text(hjust = 1,
                               vjust = 0.5)
    )
}

gg.qqplot(gwas_data$P,
          ci = NA) #remove confidence intervals with 'NA'
```


