---
title: "Violin plots"
output:
  html_document:
    toc: false
    number_sections: false
    df_print: paged
    code_download: true
    highlighter: null
---

```{r setup, eval=TRUE, include=FALSE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
chooseCRANmirror(graphics=FALSE, ind=133)
source("source/plots-overview.R")
```
___

Page last updated: `r format(Sys.time(), '%d %B, %Y')`

\  

# Examples {#violin_plots .tabset}

## Violin plot {#violin}
```{r violin, eval=TRUE, include=TRUE, echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.align='center', comment=""}
##### Violin plot
ggplot(data = movies, 
       aes(x = factor(Genre), y = rating)) + 
  xlab("") + 
  ylab("Rating (out of 10") +
  geom_violin(color = discrete_wes_pal[1],
              fill = discrete_wes_pal[1], 
              alpha = 0.8) +
  stat_summary(fun.y = median, geom ='point') +
  my_theme() +
  theme(
    axis.text.x = element_text(angle = 90,
                               hjust = 1,
                               vjust = 0.5),
    axis.text.y = element_text(hjust = 1,
                               vjust = 0.5)
    )
```
